### ISSUE TITLE
This repository is empty

### ISSUE THREAD

**Issue by karliky** [sergigp/scala-kata-boilerplate#1]
Please upload the code

**Comment by rgomezcasas** [comment]
Yes please, very important

**Comment by karliky** [comment]
Can't continue with my project because of this

**Comment by rgomezcasas** [comment]
Same, please update

**Comment by karliky** [comment]
can we have an ETA of this? Our team is currently blocked and we don't know where to buy pipebenders

**Comment by rgomezcasas** [comment]
Yes please... And if you can use https://t6.github.io/from-scala/ please

**Comment by karliky** [comment]
please

**Comment by karliky** [comment]
Any update on this?

**Comment by rgomezcasas** [comment]
Please?

**Comment by karliky** [comment]
Ok, I saw you just uploaded the code.
